spring:
  application:
    name: SecureService
  server:
    port: 8088
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false

# 'Development' profile
---
spring:
  config:
    activate:
      on-profile: Development
  datasource:
    url: jdbc:mariadb://localhost:3306/dbAssessment
    username: usAssessment
    password: mU5ic4lAss3ssm3nt
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
hibernate:
  dialect: org.hibernate.dialect.MariaDBDialect
logging:
  level:
    org:
      hibernate:
        SQL: error
        type:
          descriptor:
            sql: trace
    root: info

# 'Test' profile
---
spring:
  config:
    activate:
      on-profile: Test
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor:
            sql: trace
    root: info